	.PAGE
;
; Messages -
;
ESCKMS:	DC	'ESC' [0]
CTRLMS:	DC	'CTRL-' [0]
NONEMS:	DC	'[NONE]' [0]
RUBMS:	DC	'DEL' [0]
HGHMSG:	DC	'ESC-' [0]
SEPMSG:	DC	'  !!  ' [0]
OTDVMS:	DC	'DISPLAY ON PRINTER (0) OR CONSOLE (1) ?' [0]

COMMSG:	DC	'COM'
;
MAKERR:	DC	[13] [10] 'NO DIR SPACE$'
NONAME:	DC	[CR] [LF] 'NO INPUT FILE SPECIFIED$'
NOFILE:	DC	[13] [10] 'INPUT FILE NOT FOUND$'
WMSG:	DC	[13] [10] 'NO DISK SPACE$'
RMSG:	DC	[13] [10] 'READ ERROR$'
CLSERR:	DC	[13] [10] 'CLOSE ERROR$'
;
CHKERR:	DC	[CR] [LF] '*** WARNING - VEDIT CHECKSUM ERROR ***' [CR] [LF]
	DCS	[CR] [LF] '*** PRESS RETURN TO CONTINUE OR CTRL-C TO STOP  ***'
;
	IF	CRTVRS, [
BDSYMS:	DC	'*** INCOMPATIBLE VERSIONS OF VDSETCRT AND VEDIT ***' [CR] [LF] '$'
TBLMSG:	DC	'*** CRT.TBL NOT FOUND, OR BAD FORMAT ***' [CR] [LF] '$'
	]
	IFNOT	CRTVRS, [
BDSYMS:	DC	'*** INCOMPATIBLE VERSIONS OF VEDSET AND VEDIT ***' [CR] [LF] '$'
	]
VALMSG:	DC	'*** INVALID CONTROL CHARACTER ***'
CRLF:	DCS	[13] [10]
DUPMSG:	DC	'*** CONTROL CODE ALREADY USED ***'
	DCS	[CR] [LF]
NUMERR:	DC	[CR] [LF] '*** NUMERIC VALUE OUT OF RANGE ***'
	DCS	[CR] [LF]
;
INIMSG:	DC	[CR] [LF] [CR] [LF]

	IF	CRTVRS,[
	DC	'VDSETCRT'
]
	IFNOT	CRTVRS,[
	DC	'VEDSET'
]
	DC	' TASKS:' [CR] [LF]
	DC	[CR] [LF] '(1)  PERFORM ALL NEW KEYBOARD LAYOUT'
	DC	[CR] [LF] '(2)  ADD ALTERNATE KEYS TO EXISTING LAYOUT'
	DC	[CR] [LF] '(3)  SET SPECIAL CHARACTERS'
	DC	[CR] [LF] '(4)  SET ES & EP PARAMETERS'
	DC	[CR] [LF] '(5)  SET SCREEN PARAMETERS'
	DC	[CR] [LF] '(6)  SET OTHER PARAMETERS'
	DC	[CR] [LF] '(7)  SET SIGNON MESSAGE'
	DC	[CR] [LF] '(8)  DISPLAY OR PRINT KEYBOARD LAYOUT'
	DC	[CR] [LF] '(9)  CUSTOMIZATION COMPLETE, RETURN TO OPERATING SYSTEM'
	DCS	[CR] [LF] [CR] [LF] 'ENTER OPTION NUMBER (1 - 9) '
;
;
SONMSG:	DCS	[CR] [LF] 'ENTER SIGNON MESSAGE (MAX 64 CHARACTERS)?                      !'[CR] [LF]
;
;
ES1MSG:	DB	CR,LF, CR,LF, CR,LF
	DC	'          *** KEYBOARD LAYOUT CUSTOMIZATION ***' [CR] [LF]
	DCS	[CR] [LF] 'ENTER ESCAPE LEAD-IN CHARACTER  # 1 '
ES2MSG:	DCS	'ENTER ESCAPE LEAD-IN CHARACTER  # 2 '
;
ES3MSG:	DCS	'ENTER COMMON 2ND CHARACTER # 1 IN ESCAPE SEQUENCE '
ES4MSG:	DCS	'ENTER COMMON 2ND CHARACTER # 2 IN ESCAPE SEQUENCE '
;
ULCMSG:	DC	[CR] [LF] 'UPPER & LOWER CASE ESCAPE SEQUENCES EQUIVALENT ? '
	DCS	'(0 = NO, 1 = YES) '
;
;DCS	[CR] [LF] '0 - NEVER, 1 - ESCAPE SEQUENCES, 2 - BIT 7 CHARACTERS, 3 - BOTH ? '
;
MESSAG:	DC	[CR] [LF] 'NOTE: TYPE "B" TO START OVER FROM BEGINNING'
	DC	[CR] [LF] [CR] [LF] 'TYPE CONTROL CHARACTERS FOR'
MESSG1:	DCS	[CR] [LF] '[HOME] '
	DCS	'[ZEND] '
	DCS	'[CURSOR UP] '
	DCS	'[CURSOR DOWN] '
	DCS	'[CURSOR RIGHT] '
	DCS	'[CURSOR LEFT] '
	DCS	'[BACK TAB] '
	DCS	'[TAB CURSOR] '
	DCS	'[ZIP] '
	DCS	'[NEXT LINE] '
	DCS	'[LINE TOGGLE] '
	DCS	'[SCROLL UP] '
	DCS	'[SCROLL DOWN] '
	DCS	'[SCROLL RIGHT '
	DCS	'[SCROLL LEFT] '
	DCS	'[PREVIOUS WORD] '
	DCS	'[NEXT WORD] '
	DCS	'[PREVIOUS PARAGRAPH] '
	DCS	'[NEXT PARAGRAPH] '
	DCS	'[PAGE UP] '
	DCS	'[PAGE DOWN] '
	DCS	'[SCREEN TOGGLE] '
	DCS	'[BACKSPACE] '
	DCS	'[DELETE] '
	DCS	'[ERASE TO END OF LINE] '
	DCS	'[ERASE LINE] '
	DCS	'[DEL PREVIOUS WORD] '
	DCS	'[DEL NEXT WORD] '
	DCS	'[UNDO] '
	DCS	'[TAB CHARACTER] '
	DCS	'[NEXT CHAR LITERAL] '
	DCS	'[SET INSERT MODE] '
	DCS	'[RESET INSERT MODE] '
	DCS	'[SWITCH INSERT MODE] '
	DCS	'[REPEAT] '
	DCS	'[INDENT] '
	DCS	'[UNDENT] '
	DCS	'[FIND] '
	DCS	'[REPLACE] '
	DCS	'[CANCEL] '
	DCS	'[COPY TO TEXT REGISTER] '
	DCS	'[MOVE TO TEXT REGISTER] '
	DCS	'[INSERT TEXT REGISTER] '
	DCS	'[PRINT TEXT BLOCK] '
	DCS	'[SET TEXT MARKER] '
	DCS	'[GOTO TEXT MARKER] '
	DCS	'[FORMAT PARAGRAPH] '
	DCS	'[VISUAL ESCAPE] '
	DCS	'[VISUAL EXIT] '
	DCS	'[MACRO] '
	DCS	'[RESTART EDITOR] '
	DCS	'[HELP] '
;
	DB	00		;End of questions.
;
;
TBQMSG:	DCS	[CR] [LF] 'USE THE DEFAULT TAB POSITIONS? (Y OR N) '
TABMSG:	DCS	'ENTER UP TO 33 TAB POSITIONS IN DECIMAL ' [CR] [LF]
INSMSG:	DCS	[CR] [LF] 'BEGIN IN INSERT MODE (0=NO, 1=YES) '
;
CHTMSG:	DCS	[CR] [LF] 'HEX CODE FOR SCREEN CONTINUATION CHARACTER   (2D) '
	DCS	'HEX CODE FOR COMMAND ESCAPE CHARACTER        (1B) '
	DCS	'HEX CODE FOR COMMAND ITERATION LEFT BRACKET  (5B) '
	DCS	'HEX CODE FOR COMMAND ITERATION RIGHT BRACKET (5D) '
	DCS	'HEX CODE FOR SEARCH PATTERN MATCH CHARACTER  (7C) '

	IF	MEMVRS, [
	DCS	'HEX CODE FOR CURSOR CHARACTER (5F) '
	DCS	'HEX CODE FOR SCREEN CLEAR CHARACTER (20) '
	DCS	'HEX CODE FOR STATUS LINE CHARACTER (2D) '
	DCS	'HEX CODE FOR TAB EXPAND CHARACTER (20) '
	]
	DB	00		;End of questions.
;
STAMSG:	DCS	[CR] [LF] 'REVERSE VIDEO ON STATUS LINE  (0=NO, 1=YES) '
;
	IF	CRTVRS, [
DELMSG:	DCS	[CR] [LF] 'ENTER DECIMAL VALUE  (4MHZ = 76, 2MHZ = 38) '
	]
;
SWTMSG:	DCS	[CR] [LF] 'EXPAND TAB WITH SPACES        (0=NO, 1=YES) '
	DCS	'AUTO BUFFERING  (0=NO, 1=FORWARD, 2=AND BACKWARD) '
	DCS	'BEGIN IN VISUAL MODE          (0=NO, 1=YES) '
	DCS	'POINT PAST TEXT REG. INSERT   (0=NO, 1=YES) '
	DCS	'IGNORE UPPER/LOWER CASE DISTINCTION IN SEARCH (0=NO, 1=YES) '
	DCS	'CLEAR SCREEN ON VISUAL EXIT   (0=NO, 1=YES) '
	DCS	'REVERSE UPPER AND LOWER CASE  (0=NO, 1=YES) '
	DCS	'SUPPRESS ERROR HANDLING       (0=NO, 1=YES) '
	DCS	'USE EXPLICIT TEXT DELIMITERS  (0=NO, 1=YES) '
	DCS	'GLOBAL FILE OPERATIONS        (0=NO, 1=YES) '
	DCS	'JUSTIFY PARAGRAPHS            (0=NO, 1=YES) '
	DB	00		;End of questions.
;
PRMMSG:	IF	MEMVRS, [
	DCS	'CURSOR TYPE (0=UNDERLINE, 1=BLINK BLOCK, 2=BLOCK, 3=ATTRIBUTE) '
	DCS	'CURSOR BLINK RATE, SMALL # IS FAST (2MHZ - 20, 4MHZ - 40) '
	]
	DCS	'INDENT INCREMENT (1 - 20, SUGGEST 4) '
	DCS	'LOWER CASE CONVERT (0=NO, 1=YES, 2=CONDITIONAL) '
	DCS	'DECIMAL CODE FOR CONDITIONAL CONVERT CHARACTER (59) '
	DCS	'LINE AND COLUMN DISPLAY (0=NONE, 1=LINE, 2=COLUMN, 3=BOTH) '
	DCS	'RIGHT MARGIN FOR WORD-WRAP IN DECIMAL (0=OFF) '
	DCS	'HIGH BIT ALLOWED ON INPUT/OUTPUT (1 - 7, SUGGEST 1) '
	DCS	'CURSOR POSITIONING OPTION (0 - 2, SUGGEST 1) '
	DCS	'VIRTUAL LINE LENGTH WITH SCROLLING (40 - 255) (200) '
	DCS	'HORIZONTAL SCROLL INCREMENT (1 - 100) (20) '

	DB	00		;END OF QUESTIONS.
;
MM1MSG:	DCS	[CR] [LF] 'SIZE IN DECIMAL OF SPARE MEMORY FOR AUTO READ '
MM2MSG:	DCS	'SIZE IN DECIMAL OF FILE MOVE TRANSFERS IN K BYTES '
;
INIMS1:	DCS	[CR] [LF] 'USE DEFAULT DRIVE FOR HELP AND INIT FILES (0=NO, 1=YES) '
INIMS2:	DCS	'ENTER (0=NO) OR DRIVE # FOR HELP AND INIT FILES (0, 1 - 17) '
INIMS3:	DCS	'SHOULD VEDIT.INI FILE BE EXECUTED (0=NO, 1=YES) '
;
LINMSG:	DCS	[CR] [LF] 'ENTER NUMBER OF SCREEN LINES IN DECIMAL '
SPGMSG:	DCS	'ENTER LINE MOVEMENT FOR PAGING IN DECIMAL '
SCTPMS:	DCS	'ENTER TOP LINE FOR CURSOR IN DECIMAL '
SCBTMS:	DCS	'ENTER BOTTOM LINE FOR CURSOR IN DECIMAL '
LENMSG:	DCS	'ENTER SCREEN LINE LENGTH IN DECIMAL '
DISMSG:	DCS	'ENTER LENGTH OF DISPLAYED LINE IN DECIMAL '
;
	IF	MEMVRS, [
SCRMSG:	DCS	'ENTER ADDRESS OF SCREEN IN HEXADECIMAL '
;
IN1MSG:	DCS	[CR] [LF] 'ENTER NUMBER OF VIDEO BOARD INITIALIZATION BYTES '
IN2MSG:	DCS	'ENTER [RUBOUT] OR [CTRL-U] TO START PAIR OVER '
IN3MSG:	DCS	'ENTER DATA BYTE IN HEX '
IN4MSG:	DCS	'ENTER PORT ADDRESS IN HEX '
	]
;

